# Generated by Django 3.2 on 2023-03-28 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_inrgedientamount_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inrgedientamount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='amounts', through='recipes.InrgedientAmount', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
