# Generated by Django 3.2 on 2023-03-28 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230328_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inrgedientamount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.InrgedientAmount', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
