# Generated by Django 3.2 on 2023-05-20 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_name', inverse_match=True, message='В названии необходимо использовать буквы.', regex='^[0-9\\W]+$')], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color_format', message='Неверный формат цвета HEX #ffffff', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Цвет в HEX'),
        ),
    ]
