# Generated by Django 3.2 on 2023-03-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_subscription_exclude_self_subscribe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='exclude_self_subscribe',
        ),
    ]
