# Generated by Django 3.2 on 2023-04-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_subscription_exclude_self_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inrgedientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
    ]
