# Generated by Django 3.2 on 2023-04-01 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_inrgedientamount_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InrgedientAmount',
            new_name='IngredientAmount',
        ),
    ]
