# Generated by Django 3.2 on 2023-03-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
        ('users', '0003_auto_20230326_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited', to='recipes.Recipe', verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shoping_cart',
            field=models.ManyToManyField(blank=True, to='recipes.Ingredient', verbose_name='Список покупок'),
        ),
    ]
