# Generated by Django 3.2 on 2023-03-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230328_0756'),
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shoping_cart',
            field=models.ManyToManyField(blank=True, to='recipes.Recipe', verbose_name='Список покупок'),
        ),
    ]
